# Generated by Django 5.1.1 on 2024-10-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_author_created_at_author_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MegaEcommerce',
        ),
    ]
