# Generated by Django 5.1.1 on 2024-10-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_delete_megaecommerce'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPublisher',
            fields=[
                ('following', models.BigIntegerField(default=0)),
                ('followers', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('user_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('query', models.CharField(blank=True, max_length=500, null=True)),
                ('video_publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contents.videopublisher')),
            ],
        ),
    ]
