# Generated by Django 5.1.1 on 2024-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_videopublisher_videodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='video_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
