# Generated by Django 5.1.1 on 2024-10-07 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_videodata_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 7, 17, 16, 45, 547487, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videodata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videopublisher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 7, 17, 16, 51, 515088, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopublisher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
